### ISSUE TITLE
slideset

### ISSUE THREAD

**Issue by quasiperfect** [bqworks/slider-pro#117]
hi

is possible to show 2 slides at the same time and on navigation change both slides at the same time ?

**Comment by tomByrer** [comment]
How about using sub-divs?
```htm
 <div class="sp-slide">
  <div>
    <p>"First" slide</p>
  </div>
  <div>
    <p>slide #2 in first grouping</p>
  </div>
</div>
 <div class="sp-slide">
  <div>
    <p>slide 3</p>
  </div>
  <div>
    <p>fourth & last slide</p>
  </div>
</div>
```
You will have to add your own CSS formatting.

**Comment by quasiperfect** [comment]
@tomByrer i had the same idea i was asking because i want to know if it can be done directly or content styling is the only method

**Comment by davidghi** [comment]
Hi. It's not possible out of the box. What you could do is use the visibleSize option to show two slides at a time and use the indication here to uncenter the selected slide: https://github.com/bqworks/slider-pro/issues/80 Then, to move two slides at a time, you could override the `nextSlide` and `previousSlide` methods to increment/decrement the `selectedSlideIndex` variable by 2 instead of 1. You can find these methods in the `jquery.sliderPro.core.js` file

Cheers.

**Comment by quasiperfect** [comment]
thanks for your suggestions
