### ISSUE TITLE
issue  whit only two slides

### ISSUE THREAD

**Issue by emafari** [bqworks/slider-pro#122]
when in my sliderPro i have only two  'sp-slide' and i try to slide on the left side tha slide in not duplicated and i have empity space

**Comment by nomadOnWeb** [comment]
Same here, when using the "touch/swipe", but doesn't really slide, it move but because there isn't any image, it doesn't "jump" to the position.
Im also using the slider to display "unknown" galleries, sometimes people send only one image. I could disable the slider, but I would prefer to prevent the slide when there is only one image but still displaying the slider (like for adding dynamic elements in it).

**Comment by qahar** [comment]
I wonder why I have empty white space when swipe or use rhe arrow to slide the banner.
It was because I have 2 banner.

**Comment by qahar** [comment]
To fix this issue, set loop to false (default is true).
This will solve issue of one or two slide.

**Comment by nomadOnWeb** [comment]
Nice workaround, thanks I will test that ;)

**Comment by davidghi** [comment]
That's the solution that I would propose as well.

Cheers.
