### ISSUE TITLE
Height Percentage

### ISSUE THREAD

**Issue by theallseeingi** [bqworks/slider-pro#147]
Hi,
Im unable to set the height percentage. Any value does not work(from 1% to 100%). Removed width and then tried with height but still doesn't work.

        <script type="text/javascript">
            jQuery( document ).ready(function( $ ) {
                $( '#my-slider' ).sliderPro({
                    width: '100%',
                    height: '100%',   // this is the issue
                    arrows: true,
                    buttons: false,
                    fade: true,
                    thumbnailWidth: 288,
                    thumbnailHeight: 102
                });
            });
        </script>

Also, while we are at it, I believe I can't use calc or rem for height( or thumbnailHeight ),right? I had to fill all empty viewport with the slider and thumbnails.

Thanks in advance.

**Comment by davidghi** [comment]
Hi. If you set the height option to a percentage, you need to make sure that the element that contains the slider also has a defined height. If it doesn't, the height of that element will be 'auto', which means that it depends on the content inside, but since the content inside (the slider in this case) also depends on the height of the container, both their heights will end up being 0.

You can use `rem` or other CSS units like `vh`.

Cheers.
