### ISSUE TITLE
Responsive problem

### ISSUE THREAD

**Issue by muhammadkamran113** [bqworks/slider-pro#172]
I want the slider to be 100% in width and height according to the screen resolution. For that purpose I am using this piece of code:

width: $(window).innerWidth(),
height: $(window).innerHeight(),

its not doing responsive at all. not to the background image and not to the layers.
Am I supposed to share the link of my website here? because stackoverflow is not allowing to post question on this topic.

**Comment by ChrisIpiranga** [comment]
Did you already tryied this propertie below (width "fullWindow" for exemple)? 
Propertie: forceSize
Default value: 'none'
Available value: 'fullWidth', 'fullWindow'

**Comment by kaludjer** [comment]
If I use width: '100%' property it gives 100% width of parent element and that's okay. But when I resize the screen, image wont scale and get cropped. Anyone knows what's the problem?

**Comment by ChrisIpiranga** [comment]
Hi @kaludjer ,
Did you tried whit this different ScaleMode Properties?

**imageScaleMode**

Sets the scale mode of the main slide images (images added as background). 'cover' will scale and crop the image so that it fills the entire slide. 'contain' will keep the entire image visible inside the slide. 'exact' will match the size of the image to the size of the slide. 'none' will leave the image to its original size.

Default value: 'cover'
Available values: '**cover**', '**contain**', '**exact**' and '**none**'

**Comment by kaludjer** [comment]
Tried, but that didn't work. Here you can see two different resolutions and the problem. 
Normal: http://prnt.sc/dii3ph
Resized: http://prnt.sc/dii413

**Comment by kaludjer** [comment]
Problem solved.
orientation property was on 'horisontal', but when I use thumbnails on left side, orientation must be 'vertical'.

**Comment by davidghi** [comment]
Hi, guys. When you're using percentage values for the Width, you will need to manually set the `aspectRatio` option to a value other than -1, in order to maintain the slider's aspect ratio when the width changes, otherwise the height will not be resized accordingly.
