### ISSUE TITLE
Two sliders - arrows conflicting

### ISSUE THREAD

**Issue by kaludjer** [bqworks/slider-pro#186]
Anyone have issue with navigation arrows when have two sliders on page?

For example, you have one slider directly on page and another one that shows in modal. If you click on navigation arrow in modal slider, you can see that it triggers arrows on another slider on page (in this example - slider behind modal).

Suggestion?

**Comment by davidghi** [comment]
Hi. Are you referring to the situation where you have a slider and then open the images in the lightbox? Or do you actually have two slider instances on the same page. If you're referring to the first situation, then, it's because the slider is not paused when the ligthbox is opened. You can fix that by adding editing the code that opens the lightbox:

```
	jQuery( document ).ready(function( $ ) {
		$( ".slider-pro" ).sliderPro({
			lightbox: true,
		});

		$( ".slider-pro .sp-image" ).parent( "a" ).on( "click", function( event ) {
			event.preventDefault();
			if ( $( ".slider-pro" ).hasClass( "sp-swiping" ) === false ) {
				var sliderInstance = $( ".slider-pro" ).data( "sliderPro" ),
					isAutoplay = sliderInstance.settings.autoplay;

				$.fancybox.open( $( ".slider-pro .sp-image" ).parent( "a" ), {
					index: $( this ).parents( ".sp-slide" ).index(),
					afterShow: function() {
						if ( isAutoplay === true ) {
							sliderInstance.settings.autoplay = false;
							sliderInstance.stopAutoplay();
						}
					},
					afterClose: function() {
						if ( isAutoplay === true ) {
							sliderInstance.settings.autoplay = true;
							sliderInstance.startAutoplay();
						}
					}
					
				});
			}
		});
	});
```

If you're referring to the second situation, then please post a link to the page, so I can see exactly what happens.

Cheers!
