### ISSUE TITLE
Trouble having four slides visible in carousel

### ISSUE THREAD

**Issue by erikberger** [bqworks/slider-pro#206]
I need to have a slider with four items visible and in order from left to right (not center selected). I have ``width: 200`` and ``visibleSize: 850`` . So there should be enough room for all four items? 

See codepen: https://codepen.io/eberger/pen/jwLXEe?editors=1010

Am I doing something wrong or is this a bug?

-Erik

**Comment by davidghi** [comment]
Hi Erik. If you have the `loop` option enabled, the selected slide will be centred inside the slider, so half the slides will be after the selected image and the other half before the selected image. Since you have only 5 images, you have the first slide in the middle, then you only have two slides after it and two slides before it, with the selected slide being left aligned. If you want to have four visible images, you have two options: add at least one more image or disable the `loop` option.

Cheers!

**Comment by erikberger** [comment]
Thanks for the speedy reply David. Thanks makes sense, but unfortunately I have the requirement for a continuous loop and no way of knowing how many items there will be at a given time.
