### ISSUE TITLE
Width of slider is constant even if overflow is on

### ISSUE THREAD

**Issue by Lazarencjusz** [bqworks/slider-pro#207]
Start result
![image](https://user-images.githubusercontent.com/6573466/27517676-657dd71e-59d0-11e7-8dc6-bde77836b181.png)

After change page, overflow appears but init width of slider works like this:
![image](https://user-images.githubusercontent.com/6573466/27517670-549522cc-59d0-11e7-8bad-86df45b01f5e.png)

**Comment by davidghi** [comment]
Hi. Please post the link to the page. Cheers!

**Comment by Lazarencjusz** [comment]
Hi, sorry for late response.
http://piomar.lazarek.ayz.pl/#strona_glowna

To reproduce in chrome:
1) Unzoom view to see "Strona główna" without scroller
2) Go to "O nas"

Noticed behavior: 
Slider width is frozen and depends on width of init page (without scroller).

**Comment by davidghi** [comment]
Hi,

Are you referring to the fact that the image is cropped when the page narrows and that the height of the slider is not scaled down proportionally with the width? If so, this happens because the width is set to a percentage, and the slider can't calculate by itself the aspect ratio that it needs to maintain. For this situation you need to use the `aspectRatio` option to manually specify the aspect ratio that you want the slider to have.

Cheers
