### ISSUE TITLE
Continuous scrolling slider - Image link don't work

### ISSUE THREAD

**Issue by fsabreu** [bqworks/slider-pro#217]
Hi guys,

I'm doing a continuous scrolling slider. And I'm having some problem with image link.

Just the first link is working, the otherones do not.

I do not know if the images need to have specific css (like selected) to work.

Can you guys help me.

http://silver.quedesign.com.br/wordpress/en/interview-about-sao-paulo-app/entrevistas

Thanks

**Comment by davidghi** [comment]
Hi. I would like to take a look, but I get a "not found" page when I access the link. Please verify the URL.

Cheers

**Comment by fsabreu** [comment]
sorry I put the wrong link.

http://silver.quedesign.com.br/wordpress/en/entrevista-sobre-sao-paulo-app/entrevistas

**Comment by davidghi** [comment]
The problem is that you set the slideAnimationDuration option to 400000 (milliseconds), which causes the slider to transition very slowly from a slide to another (400 seconds), so when you're clicking on a link, the transition is likely still running. If the transition is still running, the links will be disabled in order to prevent URL navigation, since a running transition indicates that the user is navigating through the slider and wouldn't want to navigate to another page. After the transition is over, the links are enabled. If you try to set the slideAnimationDuration option to a smaller value, you will see that everything works fine.

If you want continuous scrolling, you need a different method. I'll try to come up with something, but next week.

Chers

**Comment by fsabreu** [comment]
Thanks David. 

Yeah I really need to do this slider with continuous scrolling. If you can help me with this will ba awesome.

Thanks again

**Comment by fsabreu** [comment]
Hi David, 

I still have not had success trying to change that. Did you have any progress?
thanks

**Comment by davidghi** [comment]
Hi Fellipe,

The simplest solution I could think of, without changing the core code, was to force the clicks (even if they are disabled because of the animation). Please try the code below:

```javascript
jQuery( '.sp-slide a' ).on( 'click', function() {
	var isSwiping = $( this ).parents( '.slider-pro' ).hasClass( 'sp-swiping' );

	if ( isSwiping === false ) {
		 window.location.href = $( this ).attr( 'href' );
	}
});
```

Cheers

**Comment by fsabreu** [comment]
Hi David.

That's worked perfectly.

Thank you very much!

**Comment by davidghi** [comment]
Great! You're welcome!

**Comment by fsabreu** [comment]
Hi David

I need another help from you. This code we're putting is preventing lightbox (slick lightbox) from opening correctly in the divs I've placed on some slides.

When I click on the div it goes straight to youtube instead of opening the lightbox.

it is possible to put this code only for the A tag of the image?

Thanks

**Comment by davidghi** [comment]
Hi. Does the lightbox work if you remove the JavaScript I gave you?

**Comment by fsabreu** [comment]
Hi, David

Yes it was.

**Comment by davidghi** [comment]
Please add the 'lightbox' class to all the lightbox links and then replace the previous code with this:

```javascript
jQuery( '.sp-slide a' ).not( '.lightbox' ).on( 'click', function() {
	var isSwiping = $( this ).parents( '.slider-pro' ).hasClass( 'sp-swiping' );

	if ( isSwiping === false ) {
		 window.location.href = $( this ).attr( 'href' );
	}
});
```

**Comment by fsabreu** [comment]
Thats work! 

Thanks David, you are awesome!

**Comment by davidghi** [comment]
You're welcome! :)
