### ISSUE TITLE
delay and lag  issue with  a huge number of slides

### ISSUE THREAD

**Issue by vannewman** [bqworks/slider-pro#231]
Hi @davidghi 
I made a slideshow of 400 images and slider become slow and lag, any suggestion?
Thanks for your help.

**Comment by davidghi** [comment]
Hi. Did you use lazy loading?

**Comment by vannewman** [comment]
alas!, Thank you for your quick reply @davidghi.
I did but the the problem still remain. I've created a demo with dummy data and it work fine with 40 slides but if you increase the number of slides up to 400 the problem will occur. please take a look at this. many thanks!

[20180111Demo_sliderPro.zip](https://github.com/bqworks/slider-pro/files/1621092/20180111Demo_sliderPro.zip)

**Comment by davidghi** [comment]
Hi! Sorry for the late reply! I tested your demo locally and duplicated the current slides until there were 400. I did notice a decrease in performance, as it was expected for that amount of slides, but in my opinion it wasn't significant. Can you post a screencast of your test?

**Comment by walkoffhomerun** [comment]
did you try to uses a 1x1 white pixel as the lazy load image instead of a smaller version of the same image?  that 1x1 image processes 1 time for 400 images instead of 400 small images plus 400 large images.  i did not look at your attached zip but that is how i run my example 2 slider pro with 40-50 images.

**Comment by walkoffhomerun** [comment]
i originally responded to this asking if you used a small 1x1 white image for your lazy load but you did use a small clear image so that is smart.  

try removing your lower preview images.  i have a feeling that is causing your issue because it has to load 800 images instead of 400 images.  try the slider pro without the preview images and i bet it slows up.  or keep it and also test it with the same clear image.  either way i bet it speeds up the carousel.  loading 401 images is easier than 800 images.

**Comment by vannewman** [comment]
about: 

> loading 401 images is easier than 800 images 

@walkoffhomerun, That's not a bad idea. I will give it a try .many thanks!

**Comment by walkoffhomerun** [comment]
Definitely use lazy load and when using lazy load either use a small 1x1 clear or white image or preferrably a 1x1 base64 clear image. Also, optimize image on tinyjpg or tinypng (same service) or similar online programs because even when i optimize images in photoshop tinyjpg will still cut 30% to 50% more file size in just embedded junk. It really helps out. Plus, if u do Google page speed insights tests on their website optimizing images is a massive scoring issue they use to determine a grade for ur mobile and desktop scoring. That test also gives a link at the very bottom to download all optimized files including all optimized images. Pretty simple to get optimized images that way
