### ISSUE TITLE
multiple sliders?

### ISSUE THREAD

**Issue by buddhaorange** [bqworks/slider-pro#232]
I was wondering if this is configured to allow multiple sliders to run on a page at one time?  I seem to be having a bunch of styling issues with two vertical sliders  that are literally duplicates of one another [same content, same settings, different IDs given to differentiate].  I noticed that the width of one slider is as I intended, but the other slider shoots ends up at 100px randomly if responsive is set to true.  Setting responsive to false results in just a slight difference between the widths.

I tested on the example page that comes bundled with the project.  Copied the entire div that held the sample and gave the duplicate a different ID, and now it looks like the thumbnails are weird...

**Comment by davidghi** [comment]
Hi! Yes, you should be able to use multiple sliders in the same page. The styling problems you've noticed for the thumbnails could be caused by the change of the ID, since that ID was used in the CSS selectors. For the other situations you've mentioned I would need to take a look at the page in order to understand the cause.

Cheers!
