### ISSUE TITLE
trying to copy this look with Slider Pro

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#234]
I have been using example 2 across my entire website and love it.  However, and I hate to say it.....but I found another carousel slider who has a layout option that i need help getting to work using Slider Pro instead of the other carousel slider.  See attached screen copies.  The competitive carousel is owl carousel and has 4 vertical columns on a desktop display and when going responsive to smaller screens it KEEPS THE VERTICAL HEIGHT in tact and switches from 4 columns, down to 3 then down to 2 then down to 1.  pretty simple.

stripped down demo page so david can see the setup: 
http://www.investorconstruction.com/index_test3.html

However, I HAVE emulated the look in Slider Pro but 3 problems.....

1st, when i responsive shrink down to mobile screens the height shrinks with it.  So, it keeps all 5 columns instead of just reducing the amount of columns and any text inside the columns will be too small to read.  I am trying to keep the height the same to match the owl carousel.  Example 2 is the perfect slider pro version to work with this but i need to figure a way to keep the height fixed and not shrink the entire carousel down so that it just reduces the number of columns visible.

2nd, i am really struggling to figure out WIDTH and HEIGHT.  they seem to conflict with each other.  Setting height never seems to work.  Setting width never seems to work.  I have tried pixels, percentage, and they seem to fight each other.  

3rd, when i adjust a desktop screen down on actual mobile devices the slider pro disappears.  Now, on my other example 2 carousels this does NOT happen.  I guess I need to get this column design to work first then i can figure this 3rd item out.

here is my coding to get my example to work:

```
$(document).ready(function(){
            $( '#example2' ).sliderPro({
             width: '60%', 
            /* height: '100%', */
            aspectRatio: 1.5,
	    imageScaleMode: 'none',
            visibleSize: '100%',
            arrows: true,
            buttons: false,  /* bottom image buttons for navigation */
            slideDistance: 20,
            autoSlideSize: true //required for narrower images and not have white gaps on sides of narrower images
        });
```
**photos to look at:**

**owl carousel set up with 4 columns on desktop display**
![desktop 4 column](https://user-images.githubusercontent.com/31579512/35787145-a53c5e8a-09f1-11e8-9fc2-6765ab6ee1a8.jpg)
**owl carousel beginnng to adapt down to smaller screen size.  slider STAYS SAME HEIGHT but just reduces the amount of vertical columns down**
![desktop 3 column](https://user-images.githubusercontent.com/31579512/35787148-aa81734e-09f1-11e8-8e74-2d7030d5ad00.jpg)
**owl carousel now on mobile size or phone screen. full height carousel but only 1 column visible.**
![mobile 1 column](https://user-images.githubusercontent.com/31579512/35787202-1ef73010-09f2-11e8-87b3-509a91e095b4.jpg)

**Now, my slider pro example 2 version:**

**5 column.  I cannot get the WIDTH to work correctly to get it to be 4 column**

![slider pro 5 column](https://user-images.githubusercontent.com/31579512/35787223-3f09efc8-09f2-11e8-8cfa-60a372b425fd.jpg)
**mobile screen size.  Notice how the slider pro SHRINKS IN HEIGHT. too small now.  any text would be impossible to read.  It is trying to keep all 5 columns instead of reducing the amount of columns.  Need to keep its original height but reduce the amount of columns.**

![slider pro mobile shrink height](https://user-images.githubusercontent.com/31579512/35787268-7aaa2bf6-09f2-11e8-9f50-6805b3504086.jpg)

**Comment by davidghi** [comment]
Hi,

This plugin is primarily a slider that supports a carousel-like layout, but it won't necessarily replace a carousel in any context. If Owl Carousel works better for your situation, my recommendation is to use that instead. Anyway, I will try to answer your questions:

1) The height is scaled down proportionally because you set `aspectRatio` to 1.5, so the slider will try to maintain that ratio between the width and height of the slider. To disable this behaviour, you need to set it to -1 (which is the default value).

2) The `width` and `height` options refer to the size of the individual slides, not the whole slider. Of course, if the slider has only one visible slide, then it will represent the width of the slider as well. Also, because there is only one row of slides, the `height` will often represent the height of the entire slider; if you add buttons or thumbnails below the slides, the `height` will no longer include the added height of those elements. However, if you use the `aspectRatio` option, this will override the set `height` in order to maintain the aspect ratio set by `aspectRatio`. You need to set `aspectRatio` to -1 (defaul value) if you want your `height` to be applied.

3) This shouldn't happen, unless you have some CSS media queries that hide the slider. If I try to resize your page, the slider doesn't disappear for me.

Cheers!

**Comment by walkoffhomerun** [comment]
David, I have tried all your suggestions and to be honest with you something is wrong with the coding because after changing aspectRatio to -1 it just shrinks the slider down but then that means the width and height would correct that.  however, those are NOT changing the individual sliders.  all the slider images are the same size so if i change the width to 600px it should make each slider 600px but it does NOT.  That is even deleting the height so that does not conflict.  

I have also tried centerImage = false but that does not work either.  
I have tried every option for ImageScaleMode and NONE of the images change size or scale or fit.

Setting aspectRatio to -1 did change the slider to go from keeping 6 images on the screen even in small screen sizes and allowed it to drop down to 1 center image and 2 partial side images.  Even with centerImage = false the middle image is still centered.  *** Nothing I do can i get the slider to ONLY display 1 image on a small screen.  If the width of the slider is set to 600 and the viewport size is 600 or so then only 1 slider should show but i still get multiple images.

You mentioned there must be some custom CSS media queries at play but there are not.  You can go into a browsers "web developer" section and see all the CSS and there is nothing there.  You would see media query breaks changing when screen sizes change.  but there are none.

David, is there any way YOU can try an example yourself and see if you can get the slider to do what I want it to do in the images above from the other carousel slider?

**Comment by davidghi** [comment]
Hi,

First I want to clarify some terminology, to make sure we're referring to the same elements. When I say `slider`, I'm referring to the whole structure, which contains multiple `slides`, thumbnails, arrows, buttons etc. A `slider` contains multiple `slides`, and each individual `slide` contains an `image`. A `slide` can contain more elements, but in your situation it has only one `image`.

You've set `aspectRatio` to -1, which means that the height won't be overridden anymore in order to maintain the aspect ratio, but the actual set `height` will be applied. Since you didn't set any `height`, the default value will be used, which is 300px. That's the height that the slider (and each individual slide) currently has, so it's behaving correctly.

The `width` setting is being ignored because you enabled `autoSlideSize`. As the name of the setting suggests, this setting will set the size of the slides automatically. More specifically, when the `orientation` is set to `horizontal`, the slide's height will be set according to the specified `height` value, but the width of the slides will be `auto`. This feature allows you to use both portrait and landscape images and have them equally spaced. If the `orientation` is set to `vertical`, the opposite happens: the width of the slides is fixed and their height is automatic. Since both orientations are supported, the term 'size' is used in the name of the option instead of 'width'. You still get multiple visible slides even when `width` and `visibleSize` are set to 600, because `autoSlideSize` is enabled.

The `centerImage` setting will center the image inside its slide, not the slide inside the slider. For example, if `imageScaleMode` is set to `contain`, which means that, instead of cropping it, the entire image will be visible inside its slide (and there will be blank space to the sides of the image), the `centerImage` option will center the image, as the name suggests. If it's set to `false`, the image will be aligned to the top left corner of the slide.

If you're looking for an option that will center the actual slides, not the image inside the slides, you need to use `centerSelectedSlide`. By default it's set to `true`, so, if you you want the slides to be left aligned inside the slider, you need to set it to `false`.

Regarding the CSS media queries, my statement had a different meaning. You said that the slider disappears when you resize the browser window (on a desktop) down to the size of a mobile screen (that's how I understand your initial statement; if you're referring to something else, please clarify). I've actually tested this, scaling the window down to 150px in width, and the slider didn't disappear for me. So, maybe you're referring to something else or we're seeing different things. Anyway, I know from my experience that some users had CSS to hide the slider on small screens, so I thought that maybe that was the case here. My main point here is that the slider doesn't actually disappear in my tests, so I'm not sure what you're referring to.

You've seen Example 2...If you resize the browser, the size of the slides/images doesn't change, but there are less visible slides/image. This is close to what you need. The other aspect, aligning the slides to the left instead of centering them, can be achieved by setting `centerSelectedSlide` to `false`.

Cheers!

**Comment by walkoffhomerun** [comment]
that is probably your BEST description you have ever posted.  it would be really good if you were to update your website and the github pages to include alot of this info.  that would probably help people out tremendously.  I will try some of these changes later today and see what happens.  but i do suggest updating some of the website and github pages to include alot of this info, especially many of the conflicts you mention above when 1 item supersedes another item in certain situations.

**Comment by chrisch-hh** [comment]
I ran into the same problem that percent values for `height` seems to have no effect and hides the image/slide completely. Here is an (old) example piece of code: https://codepen.io/suntrop/pen/NdpYrM?editors=1010. If you set `height` to 100%, the image/slide disappears. 

I guess the problem is that `height: 100%` is given to `div.sp-image-container` but not to all of it's parent divs. So as a workaround I used the following css to give the height to all of the parent divs:

```
.sp-masks, .sp-slides, .sp-horizontal {
    height: 100%;
}
```
