### ISSUE TITLE
Does this work in bootstrap 4 modal?

### ISSUE THREAD

**Issue by beyz** [bqworks/slider-pro#307]
I have tried but it does not seem to work in in bootstrap modal. There seems to be some responsiveness issue. When I resize the screen images appear but not when I first time open the modal. Any suggestions? Thank you in advance.

**Comment by davidghi** [comment]
Probably the slide is not visible or inside a visible container when it's instantiated, so it can't calculate its size correctly. A solution would be to call `jQuery('.slider-pro').sliderPro('resize')` after the slider or its container becomes visible, so that it can recalculate its size and display correctly.

Best,
David
