### ISSUE TITLE
FullWindow and height issue

### ISSUE THREAD

**Issue by fatsoua** [bqworks/slider-pro#312]
My basis is example 2. I modified it so that one slide is displayed at a time and fullwindow. however the height of the image is too much. how can i achieve having the images fullwindow (without loosing its quality) and with a fixed shorter height of my choice? This is what I have:
$(document ).ready(function( $ ) {
		$( '#example2' ).sliderPro({
			width: 960,
			height: 500,
			visibleSize: 'auto',			
			forceSize: "fullWindow",
			autoSlideSize: true,
			responsive: true,
			shuffle: false,
			loop: true,
			slideDistance: 0,
			arrows: false,
			buttons: false,
			keyboard: true,
			breakpoints: null
	});
});
Thank you in advance.

**Comment by davidghi** [comment]
Hi. If the Height is fixed and set to be as high as the browser's height, with `autoSlideSize` enabled, some slides might not be fully visible because their width might be bigger than the browser's width. In order to have the image fully visible, you should disable `autoSlideSize` and set `imageScaleMode` to `contain`.

Best,
David
