### ISSUE TITLE
Shouldn't init trigger after _resizeHeightTo animation is complete

### ISSUE THREAD

**Issue by wpexplorer** [bqworks/slider-pro#35]
Init fires before the _resizeHeightTo animation is complete. When working with a masonry I need to reload the masonry after the slider animates to it's correct height.

I can work around this obviously by setting a Timeout on my function hooked into init. But maybe something worth looking into so that the init callback runs exactly after the slider is finished loading and animated to it's correct height.

Hope that makes sense...

**Comment by davidghi** [comment]
I understand what you mean. The _resizeHeightTo method is called after the height of the slide becomes known, which might be after all the images from that slide are finished loading. The 'init' event, on the other hand, is fired when the slider is 'ready' and can be manipulated, so i considered it's not necessary to wait for the _resizeHeightTo animation to be complete because it might be at a much later time and most of the times you don't need to wait for it. Maybe I will create another event that will be fired when the _resizeHeightTo is complete.

**Comment by wpexplorer** [comment]
Gotcha - makes sense! Thanks ;)

**Comment by davidghi** [comment]
'resizeHeightComplete' callback was added in version 1.2.1

**Comment by wpexplorer** [comment]
Awesome, thanks!
